### ISSUE TITLE
Loading spinner forever

### ISSUE THREAD

**Issue by cassidyjames** [danrabbit/nimbus#96]
On a fresh Juno install, installing and opening Nimbus results in a spinner forever instead of it ever getting a location and showing me weather data.

**Comment by cassidyjames** [comment]
I think this is caused by https://github.com/elementary/pantheon-agent-geoclue2/pull/25, which should  be fixed by https://github.com/elementary/pantheon-agent-geoclue2/pull/31

**Comment by usersaurus** [comment]
may 14th 2020 and still not working. What's the status of the bug?

**Comment by danrabbit** [comment]
It looks like Mozilla has invalidated elementary's Mozilla Location Services key. I've submitted a request to apply for a new one. So unfortunately this effects anything using location services in elementary OS and cannot be solved within the scope of Nimbus

Closing as "Out of Scope" since this is an elementary OS issue
